# Generated by Django 5.1.3 on 2024-11-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
                ('provincia', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubi', models.CharField(max_length=100)),
                ('cursoMin', models.CharField(max_length=50)),
                ('cursoMax', models.CharField(max_length=50)),
                ('modeloEstudio', models.CharField(max_length=1)),
                ('Ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colegio', to='colegioApp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaNac', models.DateTimeField()),
                ('antiguedad', models.PositiveIntegerField()),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='colegioApp.colegio')),
            ],
        ),
    ]
